config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "categories#index"
  resources :categories, only: [:show] do
    resources :tips, only: [:index]
  end

  resources :users, only: [:show, :edit, :update]
  resources :party_challenges, only: [:update]

  resources :challenges, only: [:index, :show, :new, :create, :update] do
    resources :party_challenges, only: [:create]
  end
  resources :tips, only: [:show, :new, :create, :destroy] do
    resources :votes, only: [:create]
  end
  resources :quizzes, only: [:index, :show]

  # Creation de la partie Quiz a partir du quiz
  resources :quizzes, only: [] do
    resources :party_quizzes, only: [:new]
  end

  # Réalisation de la partie à partir du party_quiz
  resources :party_quizzes, only: [] do
    # Boucles du Quiz
    resources :answers, only: [:new, :create]
  end

  resources :places, only: [:index]

  get "*unmatched_route", to: "errors#not_found"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :party_quiz
  belongs_to :option
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :challenges
  has_many :tips
  CATEGORY = ["transport", "Food", "DIY", "Energy", "No waste", "Nature connect"]

  include PgSearch::Model
  scope :sorted, -> { order(name: :asc) }

  pg_search_scope :search,
                  against: [
                    :name
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }
  private

  def self.perform_search(keyword)
    if keyword.present?
    then Category.search(keyword)
    else Category.all
    end.sorted
  end
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :category

  has_many :party_challenges, dependent: :destroy

  include PgSearch::Model

  pg_search_scope :search,
                  against: [
                    :title,
                    :description
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }
  private

  def self.perform_search(keyword)
    if keyword.present?
      then Challenge.search(keyword)
    else
      Challenge.all
    end
  end
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

app/models/party_challenge.rb
class PartyChallenge < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
end

app/models/party_quiz.rb
class PartyQuiz < ApplicationRecord
    belongs_to :quiz
    belongs_to :user
    has_many :answers
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model

  multisearchable against: [:name, :address]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :options
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :questions
  has_many :party_quizzes, dependent: :destroy
end

app/models/tip.rb
class Tip < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :votes, dependent: :destroy
  include PgSearch::Model

  pg_search_scope :search,
                  against: [
                    :title,
                    :description
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }
  private

  def self.perform_search(keyword)
    if keyword.present?
    then Tip.search(keyword)
    else Tip.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tips
  has_many :party_challenges
  has_many :answers
  has_many :votes
  mount_uploader :photo, PhotoUploader
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :tip
  belongs_to :user
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.geocoded
      @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { place: place }),
        image_url: helpers.asset_url('octopus.png')
      }
    end
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  def index
    @tips = Tip.where(category_id: params[:category_id])
  end

  def show
    @tip = Tip.find(params[:id])
  end

  def new
    @tip = Tip.new
  end

  def create
    @tip = Tip.new(tips_params)
    @tip.user = current_user
    if @tip.save
      redirect_to category_tips_path(params[:tip][:category_id]), notice: 'Your tip as successfully been created.'
    else
      render :new
    end
  end

  def destroy
    @tip = Tip.find(params[:id])
    @tip.destroy
    redirect_to request.referrer
  end

  private

  def tips_params
    params.require(:tip).permit(:title, :description, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    # ! Voir si une partie n'est pas completed
    @party_challenges = PartyChallenge.where(completed: false, user_id: current_user)
    @count = 0
    @countdone = 0
    @countcat = 0
    @party_challenges.each do |pc|
      if (pc.updated_at.day != Time.now.day) || (pc.created_at.day == Time.now.day and pc.position == 0)
        @count += 1
      end
      if (pc.updated_at.day == Time.now.day and pc.position > 0)
        @countdone += 1
      end
    end

    # * J'appelle la function Level Up et je sauvegarde dans la DB
    level_up
    @user.save
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    @user.update(user_params)
    @user.save
    redirect_to user_path(@current_user.id)
  end

  private

  # def test1
  #   @user.total_point = @user.total_point + 17
  #   @user.save
  # end

  def level_up
    next_level = 100
    if @user.total_point >= next_level
      @user.level = @user.level + 1
      @user.total_point = @user.total_point - next_level
      @user.save
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :photo)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @tip = Tip.find(params[:tip_id])
    @vote = Vote.find_by(tip: @tip, user: current_user)
    if @vote.present?
      @vote.destroy
    else
      Vote.create(tip: @tip, user: current_user)
    end
    redirect_to request.referrer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Pour rajouter la classe active pour un lien courrant
  def current_class?(path)
    return "active" if request.path == path
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end
  
    def meta_description
      content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
    end
  
    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
      # avec une image dans vos assets ou une url absolue
      # meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
  end
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="hide-native-scrollbar">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url("fbogimg.jpg")  %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <!-- <meta name="twitter:title" content="<%= meta_title %>"> -->
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>"
    >
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.5.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.5.0/mapbox-gl.css' rel='stylesheet' />
    <!-- mapbox -->
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.5.0/mapbox-gl.css' rel='stylesheet' />
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <script src="https://kit.fontawesome.com/5034b0d787.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/scrollreveal"></script>
  </head>
  <body>
    <%# Enlever request.fullpath=='/' quand il y aura l'id user dans Catagoeries #INDEX   %>
    <% unless request.fullpath=='/users/sign_in' || request.fullpath=='/users/sign_up' %>
      <%= render 'shared/navbarmobile' %>
      <%= render 'shared/sidebar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_button.html.erb
<div id="container">
  <button class="learn-more">
    <span class="circle">
      <span class="icon arrow"></span>
    </span>
    <span class="button-text">Learn More</span>
  </button>
</div>

<!-- Button HOMEPAGE -->

<button class="button">Click Me</button>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbarmobile.html.erb
<nav class="navbar fixed-bottom navbar-light bg-light">
  <ul class="d-flex">

      <li>
        <%= link_to places_path do  %>
        <%= image_tag ("icons/placeholder.png") %>
        <% end %>
      </li>
      <li>
        <%= link_to root_path do  %>
            <%= image_tag ("icons/home.png") %>
        <% end %>
      </li>

    <li>
      <%#= link_to user_path, :class => current_class?(user_path)  do %>
        <%= link_to user_path(current_user) do %>
        <%= image_tag ("icons/user.png") %>
        <% end %>
      </li>
      <!-- <li>
        <%#= link_to url_for(:back) do %>
          <i class="fas fa-arrow-left"></i>
        <%# end %>
      </li> -->
    </ul>
  </nav>

app/views/shared/_sidebar.html.erb
<div id="mySidenav" class="sidenav hide-native-scrollbar ">
  <div class="blur"></div>
  <div class="row">
    <div class="col-10 offset-1 d-flex align-items-center mt-n4 justify-content-between">
      <p class="h4 text-white">Mon Profil</p>
      <a id="closeUserBtn" href="javascript:void(0)" class="closebtn mt-n3 text-teal">&times;</a>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-10 offset-1 mt-n3 text-center">
      <!-- Use any element to open the sidenav -->
      <%= cl_image_tag current_user.photo, class: "avatar p-1" %>
      <p class= "name text-white my-2"><%= current_user.username.capitalize %></p>
    </div>
  </div>
  <div class="row">
    <%# METTRE LE FORMULAIRE EDIT PROFIL ICI %>
    <div class="col-10 offset-1 pt-2">
      <!-- MENU TAB -->
      <nav class="nav nav-tabs" id="myTab" role="tablist">
        <a class="nav-item nav-link active d-flex flex-column justify-content-center align-items-center" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true"><i class="fas fa-sliders-h"></i><small> Paramètre</small></a>
        <a class="nav-item nav-link d-flex flex-column justify-content-center align-items-center" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false"><i class="fas fa-user-edit"></i><small>Profil</small></a>
      </nav>
      <!-- TAB CONTENT -->
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
          <div class="row">
            <div class="col-12 text-center">
            <%# LOGOUT  %>
              <%= link_to destroy_user_session_path, :method => :delete, class: " btn btn-labeled btn-primary btn-block d-flex justify-content-between align-items-center p-3 mt-4" do %>
                <p class="m-0 p-0">Se déconnecter</p> <i class="fas fa-sign-out-alt"></i>
              <% end %>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" class="hide-native-scrollbar">
          <%= simple_form_for current_user do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
                <%= f.input :username %>
                <%= f.input :photo %>
                <%= f.input :photo_cache, as: :hidden %>

            </div>
            <div class="form-actions">
              <%= f.button :submit, "Mettre à jour", class: "btn btn-primary btn-block" %>
            </div>
          <% end %>
        </div>
        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">contact...</div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_topnav.html.erb
<div id="userNav"class="container-fluid">
  <div  class="row">
    <div class="col-12 d-flex align-items-center justify-content-between p-0">
      <button type="button" id="userMenuBtn" class="btn mt-n1">
        <%= image_tag 'menubar.png' %>
      </button>
      <%= link_to url_for(:back), class: "btn btn-success mr-3" do %>
            <%= image_tag ("icons/arrow.png") %>
      <% end %>
    </div>
  </div>
</div>