config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "categories#index"
  resources :categories, only: [:show] do
    resources :tips, only: [:index]
  end

  resources :users, only: [:show, :edit, :update]
  resources :party_challenges, only: [:update]

  resources :challenges, only: [:index, :show, :new, :create, :update] do
    resources :party_challenges, only: [:create]
  end
  resources :tips, only: [:show, :new, :create, :destroy] do
    resources :votes, only: [:create]
  end
  resources :quizzes, only: [:index, :show]

  # Creation de la partie Quiz a partir du quiz
  resources :quizzes, only: [] do
    resources :party_quizzes, only: [:new]
  end

  # Réalisation de la partie à partir du party_quiz
  resources :party_quizzes, only: [] do
    # Boucles du Quiz
    resources :answers, only: [:new, :create]
  end

  resources :places, only: [:index]

  get "*unmatched_route", to: "errors#not_found"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :category

  has_many :party_challenges, dependent: :destroy

  include PgSearch::Model

  pg_search_scope :search,
                  against: [
                    :title,
                    :description
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }
  private

  def self.perform_search(keyword)
    if keyword.present?
      then Challenge.search(keyword)
    else
      Challenge.all
    end
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    
    if params[:cat].present?
      @challenges = Challenge.where(category_id: params[:cat].to_i)
    else
      @challenges = Challenge.all
    end
    
  end

  def show
    @challenge = Challenge.find(params[:id])
  end
end

app/views/challenges/index.html.erb
<section id="challenges" class="container-fluid d-flex flex-column bg-dark">
<%= render 'shared/topnav' %>
  <section id="challengesTitle" class="row px-4 my-auto">
    <div class=" name col-10 offset-1 text-center">
      <p class=" text-white  text-uppercase ">Challenges</span>
    </div>
  </section>
</section>
<section id="challengesContent" class="container-fluid d-flex page-content flex-column bg-white">
  <% if @challenges.nil? %>

  <% else %>
    <div class="row ">
      <div class="col-12">
        <!-- <p class="m-0 lead text-center">
          Trouvez vos challenges favoris ici.
        </p -->
      </div>
    </div>
    <div class="row  mb-5">

      <% @challenges.each do |challenge| %>
        <div class="col-12 mb-2">
          <%= link_to challenge_path(challenge) do %>
            <div class="category justify-content-between">
              <div class="category-text">
                <h2><%= challenge.title %></h2>
                <p><%= challenge.description.first(170)%>...</p>
              </div>
              <div class="d-flex align-items-end">
                <%= image_tag challenge.photo %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

    </div>
  <% end %>
</section>

app/views/challenges/show.html.erb
<section id="challenge" class="container-fluid d-flex flex-column bg-dark">
  <%= render 'shared/topnav' %>
  <section id="challengeTitle" class="row px-4 my-auto">
    <div class="name col-10 offset-1 text-center">
      <p class="text-white  text-uppercase "><%= @challenge.title %></h3>
    </div>
  </section>
</section>
<section id="challengeContent" class="container-fluid d-flex page-content flex-column bg-white">
  <div class="row">
    <div class="col-12">
      <div id="reward" class="">
        <div class="d-flex justify-content-around align-items-center my-2 text-center">
          <p><%= @challenge.duration %> Jours</p>
          <%= button_to "Participer", challenge_party_challenges_path(@challenge), method: :post, class: "btn btn-primary" %>
          <p><%= @challenge.points_by_step %>pts <%= image_tag('star (2).svg') %></p>
        </div>
      </div>
    </div>
    <div class="col-12 mt-4 text-center">
      <p class="description"><%= @challenge.description %></p>
    </div>
  </div>
</section>