config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "categories#index"
  resources :categories, only: [:show] do
    resources :tips, only: [:index]
  end

  resources :users, only: [:show, :edit, :update]
  resources :party_challenges, only: [:update]

  resources :challenges, only: [:index, :show, :new, :create, :update] do
    resources :party_challenges, only: [:create]
  end
  resources :tips, only: [:show, :new, :create, :destroy] do
    resources :votes, only: [:create]
  end
  resources :quizzes, only: [:index, :show]

  # Creation de la partie Quiz a partir du quiz
  resources :quizzes, only: [] do
    resources :party_quizzes, only: [:new]
  end

  # Réalisation de la partie à partir du party_quiz
  resources :party_quizzes, only: [] do
    # Boucles du Quiz
    resources :answers, only: [:new, :create]
  end

  resources :places, only: [:index]

  get "*unmatched_route", to: "errors#not_found"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :challenges
  has_many :tips
  CATEGORY = ["transport", "Food", "DIY", "Energy", "No waste", "Nature connect"]

  include PgSearch::Model
  scope :sorted, -> { order(name: :asc) }

  pg_search_scope :search,
                  against: [
                    :name
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }
  private

  def self.perform_search(keyword)
    if keyword.present?
    then Category.search(keyword)
    else Category.all
    end.sorted
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    if params[:search].present?
      @categories = Category.perform_search(params[:search])
      @tips = Tip.perform_search(params[:search])
      @challenges = Challenge.perform_search(params[:search])
      if @tips.nil?
        @tips = []
      end
      if @challenges.nil?
        @challenges = []
      end
    else
      @categories = Category.all
    end
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/views/categories/index.html.erb
<section id="categoriesIndex" class="container-fluid d-flex flex-column bg-dark">
  <%= render 'shared/topnav' %>
  <section id="categoriesTitle" class="row px-4 my-auto">
    <%# SEARCH BAR %>
    <div class="search-bar col-12 offset-1 text-center">
      <form action="/" method="get" class="search">
        <input id="search" name="search" type="text" required />
        <button class="exit" type="reset">
      </form>
    </div>
    <%# END SEARCH BAR %>
  </section>
</section>

<section id="categoriesContent" class="container-fluid h-100 d-flex page-content flex-column bg-white">
  <div class="row mb-4">
    <% unless params[:search].present? %>
    <div class="col-12">
      <div class="pressbtn">
        <%= link_to challenges_path, class: "" do %>
        <h1 class=" m-0 p-0 d-flex justify-content-between align-items-center">Challenges <%= image_tag ("icons/right-chevron.png") %></h1>
        <% end %>
      </div>
    </div>
    <div class="col-12">
      <div class="pressbtn">
        <%= link_to quizzes_path, class: "" do %>
        <h1 class=" m-0 p-0 d-flex justify-content-between align-items-center">Quizzes <%= image_tag ("icons/right-chevron.png") %></h1>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>

  <% if @tips.nil? != true || @challenges.nil? != true %>

    <% if @tips.count > 0 %>
    <div class="search-result">
      <div class="col-12 d-flex align-items-center justify-content-between ">
        <p class="h4 mx-n3">Tips</p>
      </div>
      <% @tips.each do |tip| %>
      <div class="card w-100 my-4">
        <div class="card-body mb-2">
          <div class="voteForTip  d-flex justify-content-end">
            <%= button_to tip_votes_path(tip), method: :post, class: "like-btn" do %>
            <i class="fa<%= tip.votes.present? ? "s" : "r" %> fa-heart"></i>
            <% end %>
          </div>
          <h5 class="card-title"><%= tip.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><small>Posted by: <%= tip.user.username %></small></h6>
          <p class="card-text"><%= tip.description %></p>
          <div class="bottom-tip-card d-flex justify-content-space-around align-items-center">
            <span><%= pluralize(tip.votes.count, 'likes') %></span>
            <% if tip.user == current_user %>
            <%= button_to tip_path(tip), method: :delete, class: "like-btn" do%>
            <i class='fas fa-trash-alt'></i>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% end %> <!-- Fin @tips.count > 0 -->
    <% if @challenges.count > 0 %>
    <div class="col-12 d-flex align-items-center mt-3 justify-content-between ">
      <p class="h4 mx-n3">Challenges</p>
    </div>
    <div id="challengesContentSearch" class="row mt-2">
      <% @challenges.each do |challenge| %>
      <div class="col-12 mb-2">
        <%= link_to challenge_path(challenge) do %>
        <div class="category">
          <h3><%= challenge.title %></h3>
          <%= challenge.description %>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
    <% end %> <!-- Fin @challenges.count > 0 -->

  <% end %> <!-- Fin de @tips.nil? != true || @challenges.nil? != true -->

  <%# Categories  -------------------------- %>
  <% if @categories.count > 0 %>
  <div id="vignette" class="row">
    <div class="col-12 d-flex align-items-center justify-content-between mb-4">
      <span><p class="h4">Categories</p></span>
    </div>
    <div  class="col-12">
      <div class="card-columns">
        <% @categories.each do |category| %>
          <%= link_to category_path(category) do %>
          <div class="card-homepage">
            <%= image_tag(category.photo, class: "card-img") %>
            <div class="title">
              <h3><%= category.name %></h3>
            </div>
            <div class="info">
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- Si la recherche est vide, j'affiche un message -->
  <% else %>
    <div class="col-12 text-center">
      <p class="h3 ">Votre recherche est vide.</p>
    </div>
  <% end %>

</section>

app/views/categories/show.html.erb
<section id="category" class="container-fluid d-flex flex-column bg-dark">
<%= render 'shared/topnav' %>
  <section id="categoryTitle" class="row px-4 my-auto">
    <div class=" name col-10 offset-1 text-center">
      <p class=" text-white  text-uppercase "><%= @category.name %></span>
    </div>
  </section>
</section>
<section id="categoryContent" class="container-fluid d-flex page-content flex-column bg-white">
  <div class="scrolling-wrapper-flexbox">
    <div class="card-phone ml-cpc blur">
      <%= link_to challenges_path(cat: @category.id), id: "main-btn", class: "p-0 m-0" do %>
        <div class="card-phone-content p-0 m-0 d-flex flex-column justify-content-around align-items-center " >
        <%= image_tag "icons/chall.png"  %>
          <span class="h4">Challenges</span>
        </div>
      <% end %>
      </div>
       <div class="card-phone">
      <%= link_to quizzes_path(cat: @category.id), id: "main-btn" do %>
        <div class="card-phone-content d-flex flex-column justify-content-around align-items-center">
        <%= image_tag "icons/quiz.png"  %>
          <span class="h4">Quizzes</span>
        </div>
      <% end %>
      </div>
       <div class="card-phone">
      <%= link_to category_tips_path(@category), id: "main-btn" do %>
        <div class="card-phone-content mr-cpc d-flex flex-column justify-content-around align-items-center">
        <%= image_tag "icons/tips.png"  %>
          <span class="h4">Conseils</span>
        </div>
      <% end %>
    </div>
  </div>
</section>