config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "categories#index"
  resources :categories, only: [:show] do
    resources :tips, only: [:index]
  end

  resources :users, only: [:show, :edit, :update]
  resources :party_challenges, only: [:update]

  resources :challenges, only: [:index, :show, :new, :create, :update] do
    resources :party_challenges, only: [:create]
  end
  resources :tips, only: [:show, :new, :create, :destroy] do
    resources :votes, only: [:create]
  end
  resources :quizzes, only: [:index, :show]

  # Creation de la partie Quiz a partir du quiz
  resources :quizzes, only: [] do
    resources :party_quizzes, only: [:new]
  end

  # Réalisation de la partie à partir du party_quiz
  resources :party_quizzes, only: [] do
    # Boucles du Quiz
    resources :answers, only: [:new, :create]
  end

  resources :places, only: [:index]

  get "*unmatched_route", to: "errors#not_found"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tip.rb
class Tip < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :votes, dependent: :destroy
  include PgSearch::Model

  pg_search_scope :search,
                  against: [
                    :title,
                    :description
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }
  private

  def self.perform_search(keyword)
    if keyword.present?
    then Tip.search(keyword)
    else Tip.all
    end
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  def index
    @tips = Tip.where(category_id: params[:category_id])
  end

  def show
    @tip = Tip.find(params[:id])
  end

  def new
    @tip = Tip.new
  end

  def create
    @tip = Tip.new(tips_params)
    @tip.user = current_user
    if @tip.save
      redirect_to category_tips_path(params[:tip][:category_id]), notice: 'Your tip as successfully been created.'
    else
      render :new
    end
  end

  def destroy
    @tip = Tip.find(params[:id])
    @tip.destroy
    redirect_to request.referrer
  end

  private

  def tips_params
    params.require(:tip).permit(:title, :description, :category_id)
  end
end

app/views/tips/index.html.erb
<section id="tips" class="container-fluid d-flex flex-column bg-dark">
<%= render 'shared/topnav' %>
  <section id="tipsTitle" class="row px-4 my-auto">
    <div class="name col-10 offset-1 text-center">
      <p class="text-uppercase">Conseils</p>
    </div>
  </section>
</section>
<section id="tipsContent" class="container-fluid h-100 d-flex page-content flex-column bg-white">

  <div class="cta-over-section">
    <%= link_to "Ajouter votre conseil", new_tip_path, class: "btn btn-block btn-primary" %>
  </div>

    <% @tips.reverse_each do |tip| %>
      <div class="card my-4 scrollh">
        <div class="card-body ">
          <div class="voteForTip d-flex justify-content-end">
            <span><%= pluralize(tip.votes.count, '') %></span>
            <%= button_to tip_votes_path(tip), method: :post, class: "like-btn" do %>
              <i class="fa<%= tip.votes.present? ? "s" : "r" %> fa-heart"></i>
            <% end %>
          </div>
          <h5 class="card-title mb-0"><%= tip.title %></h5>
          <small class="card-subtitle mt-n4 text-muted">Posté par: <%= tip.user.username %></small>
          <p class="card-text mt-4"><%= tip.description.first(35)%>...</p>
          <div class="bottom-tip-card d-flex justify-content-space-around align-items-center">
            <%= link_to "Voir plus", tip_path(tip)%>
            <% if tip.user == current_user %>
              <%= button_to tip_path(tip), method: :delete, class: "like-btn" do%>
                <i class='fas fa-trash-alt'></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</section>

app/views/tips/new.html.erb
<section id="tips" class="container-fluid d-flex flex-column bg-dark">
<%= render 'shared/topnav' %>
  <section id="tipsTitle" class="row px-4 my-auto">
    <div class="name col-10 offset-1 text-left">
      <p class="text-uppercase">Votre conseil</p>
    </div>
  </section>
</section>
<section id="tipsContent" class="fixed container-fluid h-100 d-flex page-content flex-column bg-white">
<div id="tipForm" class="container mt-4 padding-100 px-5">
  <div class="row h-100 justify-content-center align-items-center">
    <div class="col-xl-6 col-lg-8 col-md-8 col-sm-10 form">
      <%= simple_form_for @tip do |f| %>
        <%= f.input :title, placeholder: 'Title' %>
        <%= f.input :description, placeholder: 'Description' %>
        <%= f.association :category, include_blank: false %>
        <%= f.button :submit, class: "btn btn-primary btn-block text-primary-dark mt-5" %>
      <% end %>

    </div>
  </div>
</div>
</section>

app/views/tips/show.html.erb
<section id="tips" class="container-fluid d-flex flex-column bg-dark">
<%= render 'shared/topnav' %>
  <section id="tipTitle" class="row px-4 my-auto">
    <div class="name col-10 offset-1 text-center">
     <p class=""><%= @tip.title %></p>
    </div>
  </section>
</section>
<section id="tipsContent" class=" container-fluid h-100 d-flex page-content flex-column bg-white">
  <div class="container">

        <div class="card my-4 scrollh">
          <div class="card-body ">

            <small class="card-subtitle mt-n4 text-muted">Posted by: <%= @tip.user.username %></small>
            <p class="card-text mt-4"><%= @tip.description %></p>
            <div class="bottom-tip-card d-flex justify-content-space-between align-items-center ">
              <div class="voteForTip d-flex align-items-center ">
                <span><%= pluralize(@tip.votes.count, '') %></span>
                  <%= button_to tip_votes_path(@tip), method: :post, class: "like-btn" do %>
                    <i class="fa<%= @tip.votes.present? ? "s" : "r" %> fa-heart"></i>
                  <% end %>
                </div>
                <% if @tip.user == current_user %>
                  <%= button_to tip_path(@tip), method: :delete, class: "like-btn" do%>
                  <i class='fas fa-trash-alt'></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <div class="tipBtnBack d-flex justify-content-center">
        <div class="row">
           <%= link_to "<< Back", category_tips_path(@tip.category_id), class: "btn btn-block btn-primary mb-5" %>

          </div>
        </div>
      </div>
</section>